-- Add user_votes table for tracking one vote per user (upvote or downvote)
-- Run this in your Supabase SQL Editor

-- Create user_votes table
create table if not exists user_votes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  post_id bigint references forum_posts(id) on delete cascade,
  comment_id bigint references forum_comments(id) on delete cascade,
  vote_type int not null check (vote_type in (1, -1)), -- 1 for upvote, -1 for downvote
  voted_at timestamptz default now(),
  constraint user_votes_unique_post unique (user_id, post_id),
  constraint user_votes_unique_comment unique (user_id, comment_id),
  constraint user_votes_one_target check ((post_id is not null and comment_id is null) or (post_id is null and comment_id is not null))
);

-- Enable RLS
alter table user_votes enable row level security;

-- User votes policies (users can read all votes, insert/delete/update their own)
create policy "user_votes_read" on user_votes
  for select using (true);

create policy "user_votes_insert" on user_votes
  for insert with check (auth.uid() = user_id);

create policy "user_votes_delete" on user_votes
  for delete using (auth.uid() = user_id);

create policy "user_votes_update" on user_votes
  for update using (auth.uid() = user_id);
