-- Create doctor_ratings table for storing user-submitted ratings
-- Run this in the Supabase SQL editor for the project's database

create table if not exists doctor_ratings (
  id bigint generated by default as identity primary key,
  doctor_name text not null,
  rating int not null check (rating >= 1 and rating <= 5),
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz default now()
);

-- Optional: basic RLS policy allowing authenticated users to insert their own ratings
alter table doctor_ratings enable row level security;

create policy "doctor_ratings_insert_auth" on doctor_ratings
  for insert with check (auth.uid() = user_id);

create policy "doctor_ratings_read_public" on doctor_ratings
  for select using (true);

create policy "doctor_ratings_delete_own" on doctor_ratings
  for delete using (auth.uid() = user_id);

-- Note: adjust policies depending on desired privacy and moderation workflow
