-- Migration: Add vote_type support to user_votes table
-- This allows both upvotes and downvotes with one vote per user
-- Run this in your Supabase SQL Editor

-- If you already created user_votes table without vote_type, drop it first
-- DROP TABLE IF EXISTS user_votes CASCADE;

-- Then create/recreate the table with vote_type
CREATE TABLE IF NOT EXISTS user_votes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  post_id bigint REFERENCES forum_posts(id) ON DELETE CASCADE,
  comment_id bigint REFERENCES forum_comments(id) ON DELETE CASCADE,
  vote_type int NOT NULL CHECK (vote_type IN (1, -1)), -- 1 for upvote, -1 for downvote
  voted_at timestamptz DEFAULT now(),
  CONSTRAINT user_votes_unique_post UNIQUE (user_id, post_id),
  CONSTRAINT user_votes_unique_comment UNIQUE (user_id, comment_id),
  CONSTRAINT user_votes_one_target CHECK ((post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL))
);

-- Enable RLS
ALTER TABLE user_votes ENABLE ROW LEVEL SECURITY;

-- Drop old policies if they exist
DROP POLICY IF EXISTS "user_votes_read" ON user_votes;
DROP POLICY IF EXISTS "user_votes_insert" ON user_votes;
DROP POLICY IF EXISTS "user_votes_delete" ON user_votes;
DROP POLICY IF EXISTS "user_votes_update" ON user_votes;

-- Create RLS policies
CREATE POLICY "user_votes_read" ON user_votes
  FOR SELECT USING (true);

CREATE POLICY "user_votes_insert" ON user_votes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user_votes_delete" ON user_votes
  FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "user_votes_update" ON user_votes
  FOR UPDATE USING (auth.uid() = user_id);

-- If you need to migrate existing votes (if you had the old structure):
-- UPDATE user_votes SET vote_type = 1 WHERE vote_type IS NULL;
