
// Localized Filipino Diet Suggestions
const filipinoFoods = [
  'Malunggay (Moringa)',
  'Bangus (Milkfish)',
  'Munggo (Mung Beans)',
  'Ampalaya (Bitter Melon)',
  'Talong (Eggplant)',
  'Kamote (Sweet Potato)',
  'Gulay (Vegetables)',
];

// Localized Exercise Suggestions
const filipinoExercises = [
  'Walking around barangay',
  'Stretching routines',
  'Low-intensity aerobics',
  'Dancing (Tinikling, Zumba)',
  'Yoga',
];

// Mood-based Recommendations (activities and general tips)
const moodRecommendations = {
  'Happy': ['Go for a walk', 'Share your story in the forum', 'Try a new recipe'],
  'Tired': ['Rest', 'Hydrate well', 'Eat iron-rich foods like monggo and malunggay'],
  'Anxious': ['Meditation', 'Deep breathing', 'Talk to a friend', 'Eat omega-3 rich foods'],
  'Sad': ['Light exercise', 'Call a loved one', 'Eat omega-3 and magnesium-rich foods'],
  'Energetic': ['Channel energy into exercise', 'Meal prep for the week', 'Try strength training'],
  'Irritable': ['Practice mindfulness', 'Stay hydrated', 'Avoid caffeine and sugar'],
  'Calm': ['Maintain your routine', 'Light stretching', 'Balanced meals'],
  'Stressed': ['Yoga', 'Deep breathing exercises', 'Fiber-rich meals', 'Avoid processed foods'],
  'Neutral': ['Stay active', 'Keep a balanced diet', 'Track your progress'],
};

// ========================================
// MOOD-BASED FOOD RECOMMENDATIONS FOR PCOS
// Tailored Filipino recipes based on mood
// ========================================

const moodBasedFoodRecommendations = {
  'Happy': {
    'focus': 'Balanced feel-good meals with moderate protein, complex carbohydrates, and anti-inflammatory ingredients to sustain positive mood and stable glucose levels in PCOS.',
    'tips': [
      'Include omega-3 rich foods for sustained mood',
      'Choose complex carbs over simple sugars',
      'Add colorful vegetables for antioxidants',
    ],
    'recipes': [
      {
        'name': 'Grilled Bangus with Ensaladang Talong',
        'description': 'Heart-healthy Filipino dish rich in omega-3 fatty acids and fiber that supports insulin balance and hormonal stability in PCOS.',
        'calories': 420,
        'protein': 34,
        'carbs': 30,
        'fat': 20,
        'fiber': 6,
        'prepTime': '15 mins',
        'cookTime': '20 mins',
        'ingredients': ['120g bangus fillet', '100g eggplant', '60g tomato', '30g red onion', '10mL calamansi juice', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Grill bangus until internal temperature reaches 63°C', 'Grill eggplant until soft, peel and chop', 'Combine eggplant with tomato, onion, calamansi, and olive oil', 'Serve with measured brown rice'],
        'benefits': ['Omega-3 for anti-inflammatory response', 'High protein for satiety', 'Moderate carbs for stability'],
      },
      {
        'name': 'Baked Chicken Inasal (Skinless)',
        'description': 'Lean protein meal with anti-inflammatory spices promoting stable glucose levels.',
        'calories': 380,
        'protein': 40,
        'carbs': 28,
        'fat': 10,
        'fiber': 3,
        'prepTime': '10 mins',
        'cookTime': '25 mins',
        'ingredients': ['120g skinless chicken breast', '10mL calamansi juice', '5g garlic', '5g ginger', '5mL annatto oil', '100g cooked red rice', '100g steamed mixed vegetables'],
        'instructions': ['Marinate chicken for 60 minutes', 'Bake at 180°C for 20-25 minutes until internal temperature reaches 75°C', 'Serve with red rice and vegetables'],
        'benefits': ['High protein improves satiety', 'Supports insulin sensitivity', 'Anti-inflammatory spices'],
      },
      {
        'name': 'Tuna and Avocado Salad',
        'description': 'Balanced healthy fats and protein combination improving appetite control and glucose stability.',
        'calories': 350,
        'protein': 30,
        'carbs': 12,
        'fat': 22,
        'fiber': 7,
        'prepTime': '10 mins',
        'cookTime': '0 mins',
        'ingredients': ['120g tuna in water drained', '70g avocado', '80g lettuce', '60g cucumber', '5mL olive oil', '10mL calamansi juice'],
        'instructions': ['Drain tuna thoroughly', 'Dice avocado and cucumber', 'Combine all ingredients and mix gently', 'Serve immediately'],
        'benefits': ['Low glycemic meal', 'Healthy fats for hormones', 'Good for weight management'],
      },
    ],
  },
  'Tired': {
    'focus': 'Iron-rich, higher complex carbohydrates, moderate protein, recovery-supportive meals to combat fatigue.',
    'tips': [
      'Prioritize iron-rich foods like monggo and leafy greens',
      'Include B-vitamins for energy production',
      'Choose slow-release carbs for sustained energy',
    ],
    'recipes': [
      {
        'name': 'Ginisang Monggo with Malunggay and Shrimp',
        'description': 'Iron-rich plant protein meal supporting fatigue recovery and glucose stability.',
        'calories': 380,
        'protein': 28,
        'carbs': 50,
        'fat': 10,
        'fiber': 12,
        'prepTime': '10 mins',
        'cookTime': '25 mins',
        'ingredients': ['150g cooked monggo', '100g shrimp', '30g malunggay leaves', '60g tomato', '5g garlic', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Sauté garlic and tomato in olive oil', 'Add shrimp and cook until pink', 'Add monggo and 60mL water', 'Simmer 5-7 minutes', 'Add malunggay before serving', 'Serve with brown rice'],
        'benefits': ['High iron for fatigue recovery', 'High fiber for glucose control', 'Moderate carbs for energy'],
      },
      {
        'name': 'Lean Beef Bistek with Brown Rice',
        'description': 'Iron-dense protein meal supporting oxygen transport and energy production.',
        'calories': 450,
        'protein': 36,
        'carbs': 44,
        'fat': 16,
        'fiber': 4,
        'prepTime': '25 mins',
        'cookTime': '15 mins',
        'ingredients': ['120g lean beef sirloin', '15mL calamansi juice', '10mL low-sodium soy sauce', '50g onion rings', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Marinate beef in calamansi and soy sauce for 20 minutes', 'Sauté beef in olive oil until internal temperature reaches 70°C', 'Add onions and cook briefly', 'Serve with brown rice'],
        'benefits': ['High iron for anemia-related fatigue', 'Complete protein for recovery', 'B-vitamins for energy'],
      },
      {
        'name': 'Camote and Boiled Egg Energy Bowl',
        'description': 'Slow-release carbohydrate meal preventing glucose crashes.',
        'calories': 400,
        'protein': 16,
        'carbs': 52,
        'fat': 14,
        'fiber': 8,
        'prepTime': '5 mins',
        'cookTime': '20 mins',
        'ingredients': ['150g boiled camote', '2 boiled eggs (100g)', '50g avocado', '1g black pepper'],
        'instructions': ['Slice camote and eggs', 'Add avocado', 'Season lightly and serve'],
        'benefits': ['Low glycemic carbs', 'Sustained energy', 'No insulin spike'],
      },
    ],
  },
  'Anxious': {
    'focus': 'Calming omega-3 rich, magnesium-containing meals to reduce cortisol and support nervous system balance.',
    'tips': [
      'Include omega-3 fatty acids from fish',
      'Add magnesium-rich foods like leafy greens',
      'Avoid caffeine and processed sugars',
    ],
    'recipes': [
      {
        'name': 'Sinigang na Bangus with Malunggay',
        'description': 'Omega-3 rich sour soup supporting anti-inflammatory pathways and mood stability.',
        'calories': 380,
        'protein': 34,
        'carbs': 32,
        'fat': 14,
        'fiber': 6,
        'prepTime': '15 mins',
        'cookTime': '30 mins',
        'ingredients': ['150g bangus belly', '30g malunggay', '100g kangkong', '60g tomato', '30g tamarind paste', '100g cooked brown rice'],
        'instructions': ['Boil tamarind paste in water', 'Add bangus and cook until internal temperature reaches 63°C', 'Add vegetables and cook until tender', 'Add malunggay before serving', 'Serve with brown rice'],
        'benefits': ['Omega-3 for mood stability', 'Vitamin C for stress reduction', 'Anti-inflammatory effects'],
      },
      {
        'name': 'Salmon with Steamed Vegetables',
        'description': 'Omega-3 rich meal supporting anti-inflammatory response and mood regulation.',
        'calories': 420,
        'protein': 38,
        'carbs': 28,
        'fat': 18,
        'fiber': 5,
        'prepTime': '10 mins',
        'cookTime': '20 mins',
        'ingredients': ['150g salmon fillet', '100g broccoli', '80g spinach', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Steam salmon until internal temperature reaches 63°C', 'Steam vegetables until tender-crisp', 'Drizzle with olive oil', 'Serve with brown rice'],
        'benefits': ['High omega-3 content', 'Magnesium from greens', 'Reduces cortisol naturally'],
      },
      {
        'name': 'Chicken Tinola with Malunggay',
        'description': 'Hydrating soup with calming ginger and nutrient-rich malunggay.',
        'calories': 380,
        'protein': 36,
        'carbs': 38,
        'fat': 10,
        'fiber': 5,
        'prepTime': '15 mins',
        'cookTime': '25 mins',
        'ingredients': ['120g skinless chicken', '80g green papaya', '30g malunggay', '5g ginger', '400mL water', '100g cooked brown rice'],
        'instructions': ['Simmer ginger in water', 'Add chicken and cook until internal temperature reaches 75°C', 'Add papaya and cook until tender', 'Add malunggay before serving', 'Serve with brown rice'],
        'benefits': ['Ginger for calming effect', 'Hydrating broth', 'Nutrient-dense malunggay'],
      },
    ],
  },
  'Sad': {
    'focus': 'Mood-boosting omega-3 rich, iron and magnesium containing meals supporting serotonin production.',
    'tips': [
      'Focus on omega-3 fatty acids for brain health',
      'Include magnesium for neurotransmitter function',
      'Add vitamin D rich foods when possible',
    ],
    'recipes': [
      {
        'name': 'Sinaing na Isda (Milkfish)',
        'description': 'Omega-3 rich comfort dish supporting mood regulation.',
        'calories': 390,
        'protein': 36,
        'carbs': 32,
        'fat': 14,
        'fiber': 5,
        'prepTime': '10 mins',
        'cookTime': '35 mins',
        'ingredients': ['150g bangus', '30g kamias', '5g garlic', '100g cooked brown rice', '80g kangkong'],
        'instructions': ['Layer fish in pot with kamias and garlic', 'Add minimal water', 'Simmer until tender', 'Serve with kangkong and brown rice'],
        'benefits': ['Omega-3 for mood support', 'Iron for energy', 'Comfort food effect'],
      },
      {
        'name': 'Dinuguan without Pork (Chicken)',
        'description': 'Iron-rich dish supporting energy and mood stability.',
        'calories': 380,
        'protein': 34,
        'carbs': 30,
        'fat': 14,
        'fiber': 4,
        'prepTime': '15 mins',
        'cookTime': '30 mins',
        'ingredients': ['150g chicken breast', '60g onion', '30mL vinegar', '5g garlic', '100g cooked brown rice'],
        'instructions': ['Sauté garlic and onion', 'Add chicken and cook thoroughly', 'Add vinegar and simmer', 'Serve with brown rice'],
        'benefits': ['Iron-rich for energy', 'B-vitamins for mood', 'Protein for serotonin production'],
      },
      {
        'name': 'Grilled Salmon with Spinach',
        'description': 'Omega-3 powerhouse meal for mood enhancement.',
        'calories': 440,
        'protein': 40,
        'carbs': 20,
        'fat': 22,
        'fiber': 6,
        'prepTime': '10 mins',
        'cookTime': '15 mins',
        'ingredients': ['150g salmon fillet', '100g spinach', '5mL olive oil', '5g garlic', '100g cooked brown rice'],
        'instructions': ['Season salmon and grill until cooked', 'Sauté spinach with garlic', 'Serve together with brown rice'],
        'benefits': ['High omega-3 content', 'Magnesium from spinach', 'Supports serotonin'],
      },
    ],
  },
  'Energetic': {
    'focus': 'High-protein, balanced carbohydrate meals to sustain energy without excess and support muscle recovery.',
    'tips': [
      'Maintain balanced macronutrients',
      'Include protein for sustained energy',
      'Stay hydrated throughout activities',
    ],
    'recipes': [
      {
        'name': 'Grilled Chicken with Quinoa Bowl',
        'description': 'High-protein meal supporting active lifestyles and muscle maintenance.',
        'calories': 450,
        'protein': 42,
        'carbs': 38,
        'fat': 14,
        'fiber': 6,
        'prepTime': '15 mins',
        'cookTime': '25 mins',
        'ingredients': ['150g chicken breast', '100g quinoa', '80g mixed vegetables', '5mL olive oil', '30g chickpeas'],
        'instructions': ['Grill chicken until internal temperature reaches 75°C', 'Cook quinoa according to package', 'Roast vegetables', 'Combine and serve'],
        'benefits': ['Complete protein source', 'Complex carbs for energy', 'Fiber for satiety'],
      },
      {
        'name': 'Tuna Steak with Sweet Potato',
        'description': 'Protein-rich meal with nutrient-dense carbohydrates.',
        'calories': 430,
        'protein': 40,
        'carbs': 36,
        'fat': 12,
        'fiber': 5,
        'prepTime': '10 mins',
        'cookTime': '20 mins',
        'ingredients': ['150g tuna steak', '120g sweet potato', '80g broccoli', '5mL olive oil'],
        'instructions': ['Sear tuna to desired doneness', 'Bake sweet potato until tender', 'Steam broccoli', 'Serve together'],
        'benefits': ['Lean protein for muscles', 'Complex carbs for sustained energy', 'Rich in vitamins'],
      },
      {
        'name': 'Lean Pork Tenderloin with Vegetables',
        'description': 'Balanced protein meal supporting active days.',
        'calories': 420,
        'protein': 38,
        'carbs': 32,
        'fat': 14,
        'fiber': 6,
        'prepTime': '10 mins',
        'cookTime': '25 mins',
        'ingredients': ['130g pork tenderloin', '100g broccoli', '80g bell peppers', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Grill pork until internal temperature reaches 70°C', 'Sauté vegetables', 'Serve with brown rice'],
        'benefits': ['Lean protein source', 'B-vitamins for energy', 'Balanced nutrients'],
      },
    ],
  },
  'Irritable': {
    'focus': 'Blood sugar stabilizing, magnesium-rich calming meals to reduce irritability and mood swings.',
    'tips': [
      'Avoid sugar and caffeine',
      'Include magnesium-rich foods',
      'Eat regularly to maintain blood sugar',
    ],
    'recipes': [
      {
        'name': 'Steamed Fish with Ginger and Vegetables',
        'description': 'Light, calming meal with anti-inflammatory ginger.',
        'calories': 340,
        'protein': 36,
        'carbs': 28,
        'fat': 10,
        'fiber': 5,
        'prepTime': '10 mins',
        'cookTime': '20 mins',
        'ingredients': ['130g white fish fillet', '10g ginger', '100g bok choy', '5mL sesame oil', '100g cooked brown rice'],
        'instructions': ['Steam fish with ginger until cooked', 'Steam bok choy until tender', 'Drizzle with sesame oil', 'Serve with brown rice'],
        'benefits': ['Ginger calms digestion', 'Magnesium from greens', 'Light and easy to digest'],
      },
      {
        'name': 'Ampalaya with Egg',
        'description': 'Blood sugar regulating bitter vegetable dish.',
        'calories': 280,
        'protein': 14,
        'carbs': 26,
        'fat': 16,
        'fiber': 7,
        'prepTime': '10 mins',
        'cookTime': '15 mins',
        'ingredients': ['150g ampalaya', '2 eggs', '5g garlic', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Sauté garlic in olive oil', 'Add sliced ampalaya and cook briefly', 'Beat eggs and pour over vegetables', 'Cook until set', 'Serve with brown rice'],
        'benefits': ['Blood sugar regulation', 'Protein for stability', 'Reduces mood swings'],
      },
      {
        'name': 'Monggo with Leafy Greens',
        'description': 'Magnesium-rich comfort meal for calming.',
        'calories': 360,
        'protein': 20,
        'carbs': 52,
        'fat': 8,
        'fiber': 14,
        'prepTime': '10 mins',
        'cookTime': '25 mins',
        'ingredients': ['150g cooked monggo', '60g spinach', '30g malunggay', '5g garlic', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Sauté garlic in olive oil', 'Add monggo and simmer', 'Add greens before serving', 'Serve with brown rice'],
        'benefits': ['High magnesium content', 'Fiber for stable energy', 'Plant protein'],
      },
    ],
  },
  'Calm': {
    'focus': 'Balanced maintenance meals with steady nutrients to maintain peaceful state.',
    'tips': [
      'Maintain regular eating schedule',
      'Include a variety of nutrients',
      'Light portions to avoid sluggishness',
    ],
    'recipes': [
      {
        'name': 'Grilled Tilapia with Tomato Salsa',
        'description': 'Light balanced meal perfect for calm days.',
        'calories': 360,
        'protein': 38,
        'carbs': 28,
        'fat': 8,
        'fiber': 3,
        'prepTime': '10 mins',
        'cookTime': '15 mins',
        'ingredients': ['130g tilapia fillet', '60g tomato', '30g onion', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Grill tilapia until internal temperature reaches 63°C', 'Mix chopped tomato and onion with olive oil', 'Serve fish with salsa and brown rice'],
        'benefits': ['Lean protein', 'Antioxidants from tomatoes', 'Balanced macros'],
      },
      {
        'name': 'Pinakbet with Tofu',
        'description': 'Traditional vegetable medley with plant protein.',
        'calories': 340,
        'protein': 18,
        'carbs': 38,
        'fat': 12,
        'fiber': 10,
        'prepTime': '15 mins',
        'cookTime': '20 mins',
        'ingredients': ['100g tofu', '60g squash', '60g sitaw', '60g ampalaya', '30g tomato', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Sauté tomato and garlic', 'Add tofu and vegetables', 'Cook until tender', 'Serve with brown rice'],
        'benefits': ['Fiber-rich vegetables', 'Plant protein', 'Multiple nutrients'],
      },
      {
        'name': 'Sardines with Vegetables',
        'description': 'Affordable omega-3 meal for daily maintenance.',
        'calories': 390,
        'protein': 26,
        'carbs': 40,
        'fat': 14,
        'fiber': 6,
        'prepTime': '5 mins',
        'cookTime': '15 mins',
        'ingredients': ['120g sardines in water', '100g mixed vegetables', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Sauté vegetables in olive oil', 'Add sardines and heat through', 'Serve with brown rice'],
        'benefits': ['Omega-3 from sardines', 'Easy to prepare', 'Budget-friendly'],
      },
    ],
  },
  'Stressed': {
    'focus': 'Cortisol-lowering, magnesium and B-vitamin rich meals to support adrenal health and reduce stress.',
    'tips': [
      'Avoid caffeine and alcohol',
      'Include B-vitamins for stress response',
      'Eat magnesium-rich foods',
    ],
    'recipes': [
      {
        'name': 'Salmon and Brown Rice Bowl',
        'description': 'Omega-3 rich stress-reducing meal.',
        'calories': 440,
        'protein': 38,
        'carbs': 40,
        'fat': 16,
        'fiber': 5,
        'prepTime': '10 mins',
        'cookTime': '20 mins',
        'ingredients': ['150g salmon', '100g cooked brown rice', '80g steamed broccoli', '30g avocado', '5mL olive oil'],
        'instructions': ['Bake or grill salmon until cooked', 'Prepare brown rice and steam broccoli', 'Arrange in bowl with avocado', 'Drizzle with olive oil'],
        'benefits': ['Omega-3 reduces cortisol', 'B-vitamins for stress', 'Magnesium from broccoli'],
      },
      {
        'name': 'Chicken and Vegetable Stir-fry',
        'description': 'Quick balanced meal for busy stressed days.',
        'calories': 380,
        'protein': 36,
        'carbs': 32,
        'fat': 12,
        'fiber': 6,
        'prepTime': '15 mins',
        'cookTime': '15 mins',
        'ingredients': ['130g chicken breast', '100g mixed vegetables', '5g garlic', '5g ginger', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Slice chicken and stir-fry with garlic and ginger', 'Add vegetables and cook until tender', 'Serve with brown rice'],
        'benefits': ['Quick to prepare', 'Ginger for calming', 'Balanced nutrients'],
      },
      {
        'name': 'Monggo with Malunggay Soup',
        'description': 'Comforting fiber-rich soup for stress relief.',
        'calories': 340,
        'protein': 20,
        'carbs': 50,
        'fat': 8,
        'fiber': 14,
        'prepTime': '10 mins',
        'cookTime': '25 mins',
        'ingredients': ['150g cooked monggo', '30g malunggay', '60g tomato', '5g garlic', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Sauté garlic and tomato', 'Add monggo and water', 'Simmer until flavors blend', 'Add malunggay before serving', 'Serve with brown rice'],
        'benefits': ['High fiber for gut health', 'Magnesium from malunggay', 'Comfort food effect'],
      },
    ],
  },
  'Neutral': {
    'focus': 'Well-rounded balanced meals for everyday maintenance and overall health.',
    'tips': [
      'Maintain variety in your diet',
      'Include all food groups',
      'Focus on whole foods',
    ],
    'recipes': [
      {
        'name': 'Chicken Tinola with Brown Rice',
        'description': 'Classic Filipino comfort soup.',
        'calories': 420,
        'protein': 36,
        'carbs': 46,
        'fat': 10,
        'fiber': 5,
        'prepTime': '15 mins',
        'cookTime': '30 mins',
        'ingredients': ['120g skinless chicken', '80g green papaya', '30g malunggay', '5g ginger', '400mL water', '100g cooked brown rice'],
        'instructions': ['Simmer ginger in water', 'Add chicken and cook until done', 'Add papaya and cook until tender', 'Add malunggay before serving', 'Serve with brown rice'],
        'benefits': ['Hydrating broth', 'Lean protein', 'Nutrient-dense vegetables'],
      },
      {
        'name': 'Grilled Fish with Mixed Vegetables',
        'description': 'Simple balanced daily meal.',
        'calories': 380,
        'protein': 36,
        'carbs': 34,
        'fat': 10,
        'fiber': 6,
        'prepTime': '10 mins',
        'cookTime': '20 mins',
        'ingredients': ['130g fish fillet', '100g mixed vegetables', '5mL olive oil', '100g cooked brown rice'],
        'instructions': ['Grill fish until cooked', 'Steam or roast vegetables', 'Serve with brown rice'],
        'benefits': ['Lean protein', 'Multiple vegetables', 'Easy preparation'],
      },
      {
        'name': 'Tofu and Vegetable Adobo',
        'description': 'Plant-based Filipino classic.',
        'calories': 320,
        'protein': 18,
        'carbs': 38,
        'fat': 12,
        'fiber': 8,
        'prepTime': '10 mins',
        'cookTime': '25 mins',
        'ingredients': ['150g firm tofu', '80g vegetables', '15mL vinegar', '5mL soy sauce', '5g garlic', '100g cooked brown rice'],
        'instructions': ['Sauté garlic', 'Add tofu and brown lightly', 'Add vinegar, soy sauce, and vegetables', 'Simmer until done', 'Serve with brown rice'],
        'benefits': ['Plant protein', 'Fiber-rich', 'Heart-healthy'],
      },
    ],
  },
};

/// Get food recommendations based on the user's current mood
Map<String, dynamic>? getFoodRecommendationsForMood(String mood) {
  return moodBasedFoodRecommendations[mood];
}

/// Get a quick list of top recipe names for a mood
List<String> getTopRecipesForMood(String mood) {
  final recommendations = moodBasedFoodRecommendations[mood];
  if (recommendations == null) return [];
  final recipes = recommendations['recipes'] as List?;
  if (recipes == null) return [];
  return recipes.map((r) => r['name'] as String).toList();
}

/// Get mood-specific tips
List<String> getMoodTips(String mood) {
  final recommendations = moodBasedFoodRecommendations[mood];
  if (recommendations == null) return [];
  return List<String>.from(recommendations['tips'] as List? ?? []);
}
